# Generated by Django 3.0.4 on 2020-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200510_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DateTimeField(verbose_name='Kiralama tarihi'),
        ),
    ]
